version: "3.8"

services:
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siav_ufps
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql

  siav-ufps:
    build:
      context: .       # Busca el Dockerfile en la raíz del proyecto
      dockerfile: Dockerfile
    image: siav-ufps:latest
    container_name: siav-ufps-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/siav_ufps?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      # Agrega aquí otras vars que uses en application-prod.properties:
      # GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, AWS_ACCESS_KEY, AWS_SECRET_KEY, etc.
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:
